name: Wake Up Server

on:
  schedule:
    # 每天世界标准时间 (UTC) 21:55 运行
    # 北京时间 (GMT+8) = UTC + 8 小时
    # 21:55 + 8小时 = 次日 05:55
    - cron: '55 21 * * *'
  # 允许手动触发测试
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to wake up the server
        run: |
          curl -sI https://anisette-v3-server-oj55.onrender.com/
